/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Fondo;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author administador
 */
public class Menu extends javax.swing.JFrame {

    public InputStream foto1 = this.getClass().getResourceAsStream("/Imagenes/park.png");

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarImagen(escritorio, foto1);
//       escritorio.setBorder(new Fondo());
        this.setExtendedState(Menu.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elegirFichero = new javax.swing.JFileChooser();
        escritorio = new javax.swing.JDesktopPane(){

        };
        jLabel1 = new javax.swing.JLabel();
        eti_ingreso = new javax.swing.JLabel();
        eti_nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        openMenuItem = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mmConfiguraciones = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        estacionamiento = new javax.swing.JMenuItem();
        lista = new javax.swing.JMenuItem();
        impreso = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Cargo:");
        escritorio.add(jLabel1);
        jLabel1.setBounds(10, 40, 140, 14);

        eti_ingreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eti_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        eti_ingreso.setText("jLabel2");
        escritorio.add(eti_ingreso);
        eti_ingreso.setBounds(60, 40, 230, 20);

        eti_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eti_nombre.setForeground(new java.awt.Color(255, 255, 255));
        eti_nombre.setText("jLabel2");
        escritorio.add(eti_nombre);
        eti_nombre.setBounds(60, 10, 230, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Nombre:");
        escritorio.add(jLabel2);
        jLabel2.setBounds(10, 10, 50, 14);

        menuBar.setBackground(new java.awt.Color(204, 255, 255));
        menuBar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/webpagehome_85808.png"))); // NOI18N
        openMenuItem.setMnemonic('f');
        openMenuItem.setText("Inicio");
        openMenuItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mbrilogout_99583.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Cerrar Sesion");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        openMenuItem.add(exitMenuItem);

        menuBar.add(openMenuItem);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/window_120069.png"))); // NOI18N
        jMenu2.setText("Menu");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/window_restore_icon_144027.png"))); // NOI18N
        jMenuItem3.setText("Principal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/searchcircularbutton_79274.png"))); // NOI18N
        jMenuItem6.setText("Buscar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folderwithdocuments_120818.png"))); // NOI18N
        jMenuItem7.setText("Informes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        menuBar.add(jMenu2);

        mmConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4124824-cog-web-options-web-preferences-web-setting-webpage_113885.png"))); // NOI18N
        mmConfiguraciones.setText("Herramientas");
        mmConfiguraciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mmConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmConfiguracionesActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit_group.png"))); // NOI18N
        jMenuItem4.setText("Agregar Usuario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mmConfiguraciones.add(jMenuItem4);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessman_add.png"))); // NOI18N
        jMenuItem8.setText("Agregar Funcionarios");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mmConfiguraciones.add(jMenuItem8);

        estacionamiento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        estacionamiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estacionamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tramites.gif"))); // NOI18N
        estacionamiento.setText("Estacionamiento");
        estacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionamientoActionPerformed(evt);
            }
        });
        mmConfiguraciones.add(estacionamiento);

        lista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        lista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/the_documents_icon.png"))); // NOI18N
        lista.setText("Lista de Funcionarios");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });
        mmConfiguraciones.add(lista);

        impreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        impreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1455554839_line-60_icon-icons.com_53339.png"))); // NOI18N
        impreso.setText("Archivos");
        impreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impresoActionPerformed(evt);
            }
        });
        mmConfiguraciones.add(impreso);

        menuBar.add(mmConfiguraciones);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help_question_4509.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Ayuda");
        editMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Question.png"))); // NOI18N
        jMenuItem2.setText("A cerca");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem2);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        int S = JOptionPane.showConfirmDialog(null, "Deseas Salir?",
                "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        if (S == JOptionPane.YES_OPTION) {
            Login aunt = new Login();
            aunt.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed
    }
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VentanaPrincipal principal = new VentanaPrincipal();
        this.escritorio.add(principal);
        principal.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mmConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmConfiguracionesActionPerformed

    }//GEN-LAST:event_mmConfiguracionesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Agregar_Usuario agg = new Agregar_Usuario();
        this.escritorio.add(agg);
        agg.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Acercade acc = new Acercade();
        this.escritorio.add(acc);
        acc.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Agregar_Empleados agg = new Agregar_Empleados();
        this.escritorio.add(agg);
        agg.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // 
        VentanaBuscar v = new VentanaBuscar();
        this.escritorio.add(v);
        v.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        VentanaInformes in = new VentanaInformes();
        this.escritorio.add(in);
        in.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        Lista lis = new Lista();
        this.escritorio.add(lis);
        lis.show();
    }//GEN-LAST:event_listaActionPerformed

    private void estacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionamientoActionPerformed
        ModificarDatos dat = new ModificarDatos();
        this.escritorio.add(dat);
        dat.show();
    }//GEN-LAST:event_estacionamientoActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
//        try {
//            String url = "C:\\Users\\MATIAS\\Desktop\\ACTIVIDAD-N-2-INGENIERIA-DE-SOFTWARE__1259__0.pdf";
//            ProcessBuilder p = new ProcessBuilder();
//            p.command("cmd.exe", "/c", url);
//            p.start();
//        } catch (Exception e) {
//            JOptionPane.showConfirmDialog(null, "Error al seleccionar archivo ");
//
//        }
    }//GEN-LAST:event_editMenuActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed

    }//GEN-LAST:event_openMenuItemActionPerformed

    private void impresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impresoActionPerformed
        int resp;
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtros = new FileNameExtensionFilter("*.PDF", "pdf");
        fc.setFileFilter(filtros);
        resp = elegirFichero.showOpenDialog(this);

        if (resp == JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(null, elegirFichero.getSelectedFile().toString());

        } else if (resp == JFileChooser.CANCEL_OPTION) {

            JOptionPane.showMessageDialog(null, "Se pulsó la opción Cancelar");
        }
//        Archivos ar = new Archivos();
//        this.escritorio.add(ar);
//        ar.show();
    }//GEN-LAST:event_impresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JFileChooser elegirFichero;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem estacionamiento;
    public static javax.swing.JLabel eti_ingreso;
    public static javax.swing.JLabel eti_nombre;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem impreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem lista;
    public static javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu mmConfiguraciones;
    private javax.swing.JMenu openMenuItem;
    // End of variables declaration//GEN-END:variables
static void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new Fondo(image));
        } catch (IOException e) {
            System.out.println("Imagen no disponible");
        }
    }

}
