/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Conexiondb;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author administador
 */
public class VentanaInformes extends javax.swing.JInternalFrame {

    Conexiondb bdm = new Conexiondb();

    /**
     * Creates new form V_Informes
     */
    public VentanaInformes() {
        initComponents();
        cargarTablas();
        int a = Menu.escritorio.getWidth() - this.getWidth();
        int b = Menu.escritorio.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCocheras = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCerra = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "INFORMES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jpane.setBackground(new java.awt.Color(0, 0, 0));
        jpane.setToolTipText("");
        jpane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tablaCocheras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaCocheras);

        jpane.addTab("COCHERAS", jScrollPane2);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaHistorial.setAutoCreateRowSorter(true);
        tablaHistorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaHistorial.setToolTipText("");
        tablaHistorial.setGridColor(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(tablaHistorial);

        jpane.addTab("HISTORIAL", jScrollPane1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));

        btnCerra.setBackground(new java.awt.Color(204, 255, 204));
        btnCerra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCerra.setText("Cerrar");
        btnCerra.setBorderPainted(false);
        btnCerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerra, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerra, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpane, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpane, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerraActionPerformed
//       this.doDefaultCloseAction();
this.dispose();
    }//GEN-LAST:event_btnCerraActionPerformed

    private void cargarTablas() {
        //carga historial
        ResultSet rs = bdm.listarHistorico();
        DefaultTableModel model = (DefaultTableModel) tablaHistorial.getModel();
        model.addColumn("Patente");
        model.addColumn("Tipo de Auto");
        model.addColumn("Piso");
        model.addColumn("Hora de Ocupacion");
        model.addColumn("Hora de Salida");
       
        try {
            while (rs.next()) {
                Double dOcup = (Double) rs.getObject("hora_ocupacion");
                Double dSal = (Double) rs.getObject("hora_salida");
                Date dateEntrada = new Date(dOcup.longValue());
                Date dateSalida = new Date(dSal.longValue());
                Object rowData[] = {rs.getObject("patente"), rs.getObject("tipo_auto"),
                    rs.getObject("piso"), dateEntrada.toString(), dateSalida.toString()};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
        //carga cocheras
        ResultSet rs2 = bdm.listarCocheras();
        DefaultTableModel modelo = (DefaultTableModel) tablaCocheras.getModel();
        modelo.addColumn("Patente");
        modelo.addColumn("Tipo de Auto");
        modelo.addColumn("Piso");
        modelo.addColumn("Hora de Ocupacion");
        try {
            while (rs2.next()) {
                Double d2 = (Double) rs2.getObject("hora_ocupacion");
                Date dateEntrada = new Date(d2.longValue());
                Object rowData2[] = {rs2.getObject("patente"), rs2.getObject("tipo_auto"), 
                    rs2.getObject("piso"), dateEntrada.toString()};
                modelo.addRow(rowData2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jpane;
    private javax.swing.JTable tablaCocheras;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
